<?php
namespace Neos\Flow\Persistence\Doctrine\Migrations;

use Doctrine\Migrations\AbstractMigration;
use Doctrine\DBAL\Schema\Schema;
use Doctrine\DBAL\Migrations\AbortMigrationException;

/**
 * Auto-generated Migration: Please modify to your needs! This block will be used as the migration description if getDescription() is not used.
 */
class Version20200518190123 extends AbstractMigration
{

    /**
     * @return string
     */
    public function getDescription(): string
    {
        return '';
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function up(Schema $schema): void
    {
        // this up() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on "postgresql".');
        
        $this->addSql('CREATE TABLE lsascha_fullcalendar_domain_model_event (persistence_object_identifier VARCHAR(40) NOT NULL, eventsource VARCHAR(40) DEFAULT NULL, title VARCHAR(255) NOT NULL, allday TINYINT(1) NOT NULL, start DATETIME NOT NULL, end DATETIME NOT NULL, rendering VARCHAR(255) DEFAULT NULL, url VARCHAR(255) DEFAULT NULL, INDEX IDX_E60D57B94A922C3 (eventsource), PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('CREATE TABLE lsascha_fullcalendar_domain_model_eventsource (persistence_object_identifier VARCHAR(40) NOT NULL, title VARCHAR(255) NOT NULL, googlecalendarid VARCHAR(255) DEFAULT NULL, color VARCHAR(255) DEFAULT NULL, backgroundcolor VARCHAR(255) DEFAULT NULL, bordercolor VARCHAR(255) DEFAULT NULL, textcolor VARCHAR(255) DEFAULT NULL, rendering VARCHAR(255) DEFAULT NULL, type INT NOT NULL, pagesource VARCHAR(255) DEFAULT NULL, PRIMARY KEY(persistence_object_identifier)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB');
        $this->addSql('ALTER TABLE lsascha_fullcalendar_domain_model_event ADD CONSTRAINT FK_E60D57B94A922C3 FOREIGN KEY (eventsource) REFERENCES lsascha_fullcalendar_domain_model_eventsource (persistence_object_identifier)');
    }

    /**
     * @param Schema $schema
     * @return void
     * @throws AbortMigrationException
     */
    public function down(Schema $schema): void
    {
        // this down() migration is autogenerated, please modify it to your needs
        $this->abortIf($this->connection->getDatabasePlatform()->getName() !== 'postgresql', 'Migration can only be executed safely on "postgresql".');
        
        $this->addSql('ALTER TABLE lsascha_fullcalendar_domain_model_event DROP FOREIGN KEY FK_E60D57B94A922C3');
        $this->addSql('DROP TABLE lsascha_fullcalendar_domain_model_event');
        $this->addSql('DROP TABLE lsascha_fullcalendar_domain_model_eventsource');
    }
}